//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auftragserfassung_Blazor.Module.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auftragserfassung_Blazor.Module.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string archiv_artikel {
            get {
                return ResourceManager.GetString("archiv_artikel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outdoors
        ///Garden
        ///Sports
        ///Grocery
        ///Automotive
        ///Outdoors
        ///Movies
        ///Garden
        ///Clothing
        ///Health
        ///Grocery
        ///Automotive
        ///Outdoors
        ///Books
        ///Health
        ///Jewelry
        ///Movies
        ///Home
        ///Kids
        ///Industrial
        ///Computers
        ///Games
        ///Toys
        ///Movies
        ///Kids
        ///Beauty
        ///Toys
        ///Toys
        ///Beauty
        ///Home
        ///Kids
        ///Beauty
        ///Books
        ///Games
        ///Electronics
        ///Health
        ///Garden
        ///Tools
        ///Health
        ///Grocery
        ///Tools
        ///Home
        ///Automotive
        ///Clothing
        ///Kids
        ///Baby
        ///Clothing
        ///Music
        ///Garden
        ///Garden
        ///Kids
        ///Shoes
        ///Automotive
        ///Grocery
        ///Electronics
        ///Computers
        ///Music
        ///Outdoors
        ///Health
        ///Games
        ///Movies
        ///Ind [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ArtikelGruppen_englisch {
            get {
                return ResourceManager.GetString("ArtikelGruppen_englisch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bag Stand
        ///Cookie Dough - Oatmeal Rasin
        ///Wine - Mas Chicet Rose, Vintage
        ///Yogurt - Assorted Pack
        ///Lettuce - Boston Bib - Organic
        ///Bagel - Plain
        ///Melon - Honey Dew
        ///Sardines
        ///Tomatoes - Grape
        ///Pork - Bacon, Double Smoked
        ///Hold Up Tool Storage Rack
        ///Cheese - Wine
        ///Rosemary - Dry
        ///Sour Puss Sour Apple
        ///Chicken - Base
        ///Anchovy Fillets
        ///Pomegranates
        ///Pop - Club Soda Can
        ///Horseradish Root
        ///Oil - Avocado
        ///Cheese - Le Cheve Noir
        ///Pickerel - Fillets
        ///Lemonade - Island Tea, 591 Ml
        ///Cheese - La Sauvagine
        ///Radish - Bla [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Artikelnamen_englisch {
            get {
                return ResourceManager.GetString("Artikelnamen_englisch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Baden-Württemberg
        ///Rheinland-Pfalz
        ///Nordrhein-Westfalen
        ///Nordrhein-Westfalen
        ///Nordrhein-Westfalen
        ///Nordrhein-Westfalen
        ///Nordrhein-Westfalen
        ///Nordrhein-Westfalen
        ///Nordrhein-Westfalen
        ///Nordrhein-Westfalen
        ///Nordrhein-Westfalen
        ///Nordrhein-Westfalen
        ///Baden-Württemberg
        ///Baden-Württemberg
        ///Baden-Württemberg
        ///Baden-Württemberg
        ///Baden-Württemberg
        ///Hessen
        ///Schleswig-Holstein
        ///Bayern
        ///Bayern
        ///Rheinland-Pfalz
        ///Bayern
        ///Baden-Württemberg
        ///Thüringen
        ///Baden-Württemberg
        ///Hessen
        ///Bayern
        ///Rheinland-Pfalz
        ///Baden-Württemberg
        ///B [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string bundesland {
            get {
                return ResourceManager.GetString("bundesland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 08/04/2019
        ///24/01/2016
        ///29/01/2019
        ///25/08/2013
        ///27/02/2021
        ///01/07/2016
        ///24/09/2018
        ///01/09/2012
        ///17/08/2017
        ///18/12/2016
        ///08/03/2021
        ///25/07/2012
        ///11/09/2019
        ///20/12/2015
        ///02/04/2017
        ///09/01/2014
        ///02/03/2020
        ///20/06/2019
        ///21/06/2016
        ///09/11/2015
        ///31/03/2015
        ///07/12/2016
        ///26/11/2016
        ///26/05/2012
        ///19/10/2019
        ///26/04/2014
        ///14/04/2019
        ///24/11/2017
        ///21/05/2014
        ///15/12/2014
        ///06/01/2017
        ///02/02/2012
        ///08/08/2019
        ///30/01/2013
        ///25/02/2019
        ///27/10/2019
        ///09/11/2019
        ///23/06/2014
        ///31/12/2015
        ///27/06/2016
        ///17/06/2013
        ///02/07/2014
        ///05/01/20 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string datum {
            get {
                return ResourceManager.GetString("datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cdowdle0@oaic.gov.au
        ///mmeins1@archive.org
        ///lmapes2@elegantthemes.com
        ///tmcgray3@msn.com
        ///epowys4@forbes.com
        ///aserjent5@tamu.edu
        ///vtullett6@omniture.com
        ///tabbets7@about.me
        ///sbusch8@trellian.com
        ///dobrollachain9@blogs.com
        ///akezora@1und1.de
        ///ncrosstonb@devhub.com
        ///dbillitteric@epa.gov
        ///vteard@multiply.com
        ///dfrottone@ox.ac.uk
        ///agresleyf@reverbnation.com
        ///mtrattlesg@github.io
        ///rgeranth@theatlantic.com
        ///clincei@berkeley.edu
        ///vstallanj@comcast.net
        ///lfirbyk@auda.org.au
        ///cambresinl@sphinn.com
        ///jmangenetm@surveymonkey. [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///GmbH
        ///OHG
        ///KG
        ///GbR
        ///AG
        ///GmbH &amp; Co.KG
        ///e.K.
        ///UG
        ///e.V.
        /// ähnelt.
        /// </summary>
        internal static string firmenRechtsformen {
            get {
                return ResourceManager.GetString("firmenRechtsformen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LI50 1938 1MY6 SXAS XV3W T
        ///PS30 VHWG 7IA8 P7QA AKJD XZFZ YAHE W
        ///GI80 LCJS NIBP WKHX MVIQ CXD
        ///LT22 1857 0883 1284 4868
        ///PT23 9829 3603 1466 1711 9039 8
        ///CY44 6663 6298 H3ET WXCY LG61 RE4V
        ///AZ90 MYPX UD23 GS9O 1X4Y 6KMH 2U3C
        ///DO59 UI5T 9576 5205 3596 8362 2257
        ///AZ65 LONL HIDI OXWM P1A5 WVWR CNTJ
        ///EE13 3751 5944 2279 4665
        ///FR94 0051 6318 02A9 NRNX RRQI M27
        ///MK11 643W MGLS SD28 M92
        ///TR60 9519 4BC3 MHSJ WCT1 12MM HI
        ///BE40 9499 2787 7261
        ///MT20 DSDM 7979 20XW YVRV NSDY NQNF EFO
        ///CR55 7875 9628 9152 6720 3
        ///GE76 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string IBAN {
            get {
                return ResourceManager.GetString("IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 588725345-2
        ///128308925-4
        ///596539648-1
        ///562503090-1
        ///552206771-3
        ///139064170-8
        ///469017637-X
        ///033195436-2
        ///933302219-8
        ///844123617-8
        ///908382631-7
        ///851001339-X
        ///167277402-0
        ///114008584-0
        ///016304782-0
        ///321606578-2
        ///657049668-9
        ///489216016-4
        ///333151052-1
        ///208552187-8
        ///665052164-7
        ///917718125-5
        ///764881792-6
        ///578415227-0
        ///839144452-X
        ///535243411-7
        ///402631075-2
        ///735675130-5
        ///306837733-1
        ///804281482-8
        ///945233351-0
        ///823739721-5
        ///683625845-8
        ///018032205-2
        ///683280850-X
        ///071308812-5
        ///547448551-4
        ///562785688-2
        ///297322926-X
        ///92067 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string Land {
            get {
                return ResourceManager.GetString("Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Landkreis Konstanz
        ///Landkreis Trier-Saarburg
        ///Städteregion Aachen
        ///Städteregion Aachen
        ///Städteregion Aachen
        ///Städteregion Aachen
        ///Städteregion Aachen
        ///Städteregion Aachen
        ///Städteregion Aachen
        ///Städteregion Aachen
        ///Städteregion Aachen
        ///Städteregion Aachen
        ///Ostalbkreis
        ///Ostalbkreis
        ///Ostalbkreis
        ///Ostalbkreis
        ///Ostalbkreis
        ///Rheingau-Taunus-Kreis
        ///Kreis Steinburg
        ///Landkreis Roth
        ///Landkreis Kelheim
        ///Landkreis Birkenfeld
        ///Landkreis Weißenburg-Gunzenhausen
        ///Landkreis Heilbronn
        ///Kyffhäuserkreis
        ///Ostalbkreis
        ///Kreis Be [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string landkreis {
            get {
                return ResourceManager.GetString("landkreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dowdle
        ///Meins
        ///Mapes
        ///McGray
        ///Powys
        ///Serjent
        ///Tullett
        ///Abbets
        ///Busch
        ///O&apos;Brollachain
        ///Kezor
        ///Crosston
        ///Billitteri
        ///Tear
        ///Frotton
        ///Gresley
        ///Trattles
        ///Gerant
        ///Lince
        ///Stallan
        ///Firby
        ///Ambresin
        ///Mangenet
        ///Tuminini
        ///Withinshaw
        ///Triggle
        ///Moukes
        ///Turville
        ///Pipkin
        ///Chatin
        ///Gonzales
        ///Bolle
        ///Libermore
        ///Consadine
        ///Goodere
        ///Ballston
        ///Barden
        ///Djordjevic
        ///Vidloc
        ///Kenwyn
        ///Paragreen
        ///Preedy
        ///Meadus
        ///Renehan
        ///Dainton
        ///Iggalden
        ///Swatland
        ///Costell
        ///Luby
        ///Lytle
        ///Apps
        ///Gasnoll
        ///Corser
        ///Clinning
        ///Dy
        ///Larmet
        ///Northey
        ///Atkirk
        ///Winsk [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string nachname_usa {
            get {
                return ResourceManager.GetString("nachname_usa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Müller
        ///Schmidt
        ///Schneider
        ///Fischer
        ///Weber
        ///Meyer
        ///Wagner
        ///Becker
        ///Schulz
        ///Hoffmann
        ///Koch
        ///Richter
        ///Bauer
        ///Schäfer
        ///Klein
        ///Wolf
        ///Schröder
        ///Neumann
        ///Schwarz
        ///Braun
        ///Zimmermann
        ///Hofmann
        ///Lange
        ///Hartmann
        ///Krüger
        ///Krause
        ///Lehmann
        ///Schmitz
        ///Meier
        ///Schmitt
        ///Werner
        ///Schmid
        ///Schulze
        ///Maier
        ///Herrmann
        ///Mayer
        ///Köhler
        ///Walter
        ///König
        ///Huber
        ///Kaiser
        ///Peters
        ///Fuchs
        ///Möller
        ///Lang
        ///Scholz
        ///Jung
        ///Weiß
        ///Hahn
        ///Keller
        ///Berger
        ///Vogel
        ///Schubert
        ///Friedrich
        ///Frank
        ///Roth
        ///Winkler
        ///Beck
        ///Günther
        ///Lorenz
        ///Baumann
        ///Franke
        ///Albrecht
        ///Lu [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string nachnamen {
            get {
                return ResourceManager.GetString("nachnamen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Obere Str. 57
        ///Avda. de la Constitución 2222
        ///Mataderos  2312
        ///120 Hanover Sq.
        ///Berguvsvägen  8
        ///Forsterstr. 57
        ///24, place Kléber
        ///C/ Araquil, 67
        ///12, rue des Bouchers
        ///23 Tsawassen Blvd.
        ///Fauntleroy Circus
        ///Cerrito 333
        ///Sierras de Granada 9993
        ///Hauptstr. 29
        ///Av. dos Lusíadas, 23
        ///Berkeley Gardens 12  Brewery
        ///Walserweg 21
        ///67, rue des Cinquante Otages
        ///35 King George
        ///Kirchgasse 6
        ///Rua Orós, 92
        ///C/ Moralzarzal, 86
        ///184, chaussée de Tournai
        ///Åkergatan 24
        ///Berliner Platz 43
        ///54, rue Royale
        ///Via Monte Bianco  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Northwind_Address {
            get {
                return ResourceManager.GetString("Northwind_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berlin
        ///México D.F.
        ///México D.F.
        ///London
        ///Luleå
        ///Mannheim
        ///Strasbourg
        ///Madrid
        ///Marseille
        ///Tsawassen
        ///London
        ///Buenos Aires
        ///México D.F.
        ///Bern
        ///Sao Paulo
        ///London
        ///Aachen
        ///Nantes
        ///London
        ///Graz
        ///Sao Paulo
        ///Madrid
        ///Lille
        ///Bräcke
        ///München
        ///Nantes
        ///Torino
        ///Lisboa
        ///Barcelona
        ///Sevilla
        ///Campinas
        ///Eugene
        ///Caracas
        ///Rio de Janeiro
        ///San Cristóbal
        ///Elgin
        ///Cork
        ///Cowes
        ///Brandenburg
        ///Versailles
        ///Toulouse
        ///Vancouver
        ///Walla Walla
        ///Frankfurt a.M.
        ///San Francisco
        ///Barquisimeto
        ///I. de Margarita
        ///Portland
        ///Bergamo
        ///Bruxelles
        ///Montr [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Northwind_City {
            get {
                return ResourceManager.GetString("Northwind_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alfreds Futterkiste
        ///Ana Trujillo Emparedados y helados
        ///Antonio Moreno Taquería
        ///Around the Horn
        ///Berglunds snabbköp
        ///Blauer See Delikatessen
        ///Blondesddsl père et fils
        ///Bólido Comidas preparadas
        ///Bon app&apos;
        ///Bottom-Dollar Markets
        ///B&apos;s Beverages
        ///Cactus Comidas para llevar
        ///Centro comercial Moctezuma
        ///Chop-suey Chinese
        ///Comércio Mineiro
        ///Consolidated Holdings
        ///Drachenblut Delikatessen
        ///Du monde entier
        ///Eastern Connection
        ///Ernst Handel
        ///Familia Arquibaldo
        ///FISSA Fabrica Inter. Salchichas S.A.
        ///Folies gourmande [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Northwind_Company_Name {
            get {
                return ResourceManager.GetString("Northwind_Company_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sales Representative
        ///Owner
        ///Owner
        ///Sales Representative
        ///Order Administrator
        ///Sales Representative
        ///Marketing Manager
        ///Owner
        ///Owner
        ///Accounting Manager
        ///Sales Representative
        ///Sales Agent
        ///Marketing Manager
        ///Owner
        ///Sales Associate
        ///Sales Representative
        ///Order Administrator
        ///Owner
        ///Sales Agent
        ///Sales Manager
        ///Marketing Assistant
        ///Accounting Manager
        ///Assistant Sales Agent
        ///Owner
        ///Marketing Manager
        ///Marketing Manager
        ///Sales Representative
        ///Sales Manager
        ///Marketing Manager
        ///Sales Manager
        ///Sales Associate
        ///Marke [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Northwind_Contact_Title {
            get {
                return ResourceManager.GetString("Northwind_Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maria Anders
        ///Ana Trujillo
        ///Antonio Moreno
        ///Thomas Hardy
        ///Christina Berglund
        ///Hanna Moos
        ///Frédérique Citeaux
        ///Martín Sommer
        ///Laurence Lebihan
        ///Elizabeth Lincoln
        ///Victoria Ashworth
        ///Patricio Simpson
        ///Francisco Chang
        ///Yang Wang
        ///Pedro Afonso
        ///Elizabeth Brown
        ///Sven Ottlieb
        ///Janine Labrune
        ///Ann Devon
        ///Roland Mendel
        ///Aria Cruz
        ///Diego Roel
        ///Martine Rancé
        ///Maria Larsson
        ///Peter Franken
        ///Carine Schmitt
        ///Paolo Accorti
        ///Lino Rodriguez
        ///Eduardo Saavedra
        ///José Pedro Freyre
        ///André Fonseca
        ///Howard Snyder
        ///Manuel Pereira
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Northwind_ContactName {
            get {
                return ResourceManager.GetString("Northwind_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Germany
        ///Mexico
        ///Mexico
        ///UK
        ///Sweden
        ///Germany
        ///France
        ///Spain
        ///France
        ///Canada
        ///UK
        ///Argentina
        ///Mexico
        ///Switzerland
        ///Brazil
        ///UK
        ///Germany
        ///France
        ///UK
        ///Austria
        ///Brazil
        ///Spain
        ///France
        ///Sweden
        ///Germany
        ///France
        ///Italy
        ///Portugal
        ///Spain
        ///Spain
        ///Brazil
        ///USA
        ///Venezuela
        ///Brazil
        ///Venezuela
        ///USA
        ///Ireland
        ///UK
        ///Germany
        ///France
        ///France
        ///Canada
        ///USA
        ///Germany
        ///USA
        ///Venezuela
        ///Venezuela
        ///USA
        ///Italy
        ///Belgium
        ///Canada
        ///Germany
        ///UK
        ///Argentina
        ///USA
        ///Germany
        ///France
        ///Mexico
        ///Austria
        ///Portugal
        ///Brazil
        ///Brazil
        ///Germany
        ///Argentina
        ///USA
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Northwind_Country {
            get {
                return ResourceManager.GetString("Northwind_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 030-0076545
        ///(5) 555-3745
        ///(171) 555-6750
        ///0921-12 34 67
        ///0621-08924
        ///88.60.15.32
        ///(91) 555 91 99
        ///91.24.45.41
        ///(604) 555-3745
        ///(1) 135-4892
        ///(5) 555-7293
        ///(171) 555-9199
        ///0241-059428
        ///40.67.89.89
        ///(171) 555-3373
        ///7675-3426
        ///(91) 555 55 93
        ///20.16.10.17
        ///089-0877451
        ///40.32.21.20
        ///011-4988261
        ///(1) 354-2535
        ///(93) 203 4561
        ///(2) 283-3397
        ///(21) 555-8765
        ///(5) 555-1948
        ///(503) 555-2376
        ///2967 3333
        ///30.59.85.11
        ///61.77.61.11
        ///(604) 555-7293
        ///(509) 555-6221
        ///069-0245874
        ///(9) 331-7256
        ///(8) 34-93-93
        ///(503) 555-9646
        ///035-6 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Northwind_Fax {
            get {
                return ResourceManager.GetString("Northwind_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 030-0074321
        ///(5) 555-4729
        ///(5) 555-3932
        ///(171) 555-7788
        ///0921-12 34 65
        ///0621-08460
        ///88.60.15.31
        ///(91) 555 22 82
        ///91.24.45.40
        ///(604) 555-4729
        ///(171) 555-1212
        ///(1) 135-5555
        ///(5) 555-3392
        ///0452-076545
        ///(11) 555-7647
        ///(171) 555-2282
        ///0241-039123
        ///40.67.88.88
        ///(171) 555-0297
        ///7675-3425
        ///(11) 555-9857
        ///(91) 555 94 44
        ///20.16.10.16
        ///0695-34 67 21
        ///089-0877310
        ///40.32.21.21
        ///011-4988260
        ///(1) 354-2534
        ///(93) 203 4560
        ///(95) 555 82 82
        ///(11) 555-9482
        ///(503) 555-7555
        ///(2) 283-2951
        ///(21) 555-0091
        ///(5) 555-1340
        ///(503) 555-68 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Northwind_Phone {
            get {
                return ResourceManager.GetString("Northwind_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 12209
        ///05021
        ///05023
        ///WA1 1DP
        ///S-958 22
        ///68306
        ///67000
        ///28023
        ///13008
        ///T2F 8M4
        ///EC2 5NT
        ///1010
        ///05022
        ///3012
        ///05432-043
        ///WX1 6LT
        ///52066
        ///44000
        ///WX3 6FW
        ///8010
        ///05442-030
        ///28034
        ///59000
        ///S-844 67
        ///80805
        ///44000
        ///10100
        ///1675
        ///08022
        ///41101
        ///04876-786
        ///97403
        ///1081
        ///05454-876
        ///5022
        ///97827
        ///
        ///PO31 7PJ
        ///14776
        ///78000
        ///31000
        ///V3F 2K1
        ///99362
        ///60528
        ///94117
        ///3508
        ///4980
        ///97219
        ///24100
        ///B-1180
        ///H1J 1C3
        ///04179
        ///SW7 1RZ
        ///1010
        ///99508
        ///50739
        ///75012
        ///05033
        ///5020
        ///1756
        ///02389-673
        ///05487-020
        ///01307
        ///1010
        ///87110
        ///42100
        ///02389-890
        ///1203
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Northwind_Postal_Code {
            get {
                return ResourceManager.GetString("Northwind_Postal_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aach
        ///Aach
        ///Aachen
        ///Aachen
        ///Aachen
        ///Aachen
        ///Aachen
        ///Aachen
        ///Aachen
        ///Aachen
        ///Aachen
        ///Aachen
        ///Aalen
        ///Aalen
        ///Aalen
        ///Aalen
        ///Aalen
        ///Aarbergen
        ///Aasbüttel
        ///Abenberg
        ///Abensberg
        ///Abentheuer
        ///Absberg
        ///Abstatt
        ///Abtsbessingen
        ///Abtsgmünd
        ///Abtsteinach
        ///Abtswind
        ///Abtweiler
        ///Achberg
        ///Achern
        ///Achim
        ///Achslach
        ///Achstetten
        ///Acht
        ///Achtelsbach
        ///Achterwehr
        ///Achtrup
        ///Adelberg
        ///Adelebsen
        ///Adelheidsdorf
        ///Adelmannsfelden
        ///Adelschlag
        ///Adelsdorf
        ///Adelsheim
        ///Adelshofen
        ///Adelshofen
        ///Adelsried
        ///Adelzhausen
        ///Adenau
        ///Adenbach
        ///Adenbüttel
        ///A [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Ort {
            get {
                return ResourceManager.GetString("Ort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 78267
        ///54298
        ///52062
        ///52064
        ///52066
        ///52068
        ///52070
        ///52072
        ///52074
        ///52076
        ///52078
        ///52080
        ///73430
        ///73431
        ///73432
        ///73433
        ///73434
        ///65326
        ///25560
        ///91183
        ///93326
        ///55767
        ///91720
        ///74232
        ///99713
        ///73453
        ///69518
        ///97355
        ///55568
        ///88147
        ///77855
        ///28832
        ///94250
        ///88480
        ///56729
        ///55767
        ///24239
        ///25917
        ///73099
        ///37139
        ///29352
        ///73486
        ///85111
        ///91325
        ///74740
        ///91587
        ///82276
        ///86477
        ///86559
        ///53518
        ///67742
        ///38528
        ///21365
        ///84166
        ///18211
        ///08626
        ///25572
        ///31855
        ///71563
        ///86444
        ///27257
        ///54689
        ///21684
        ///25560
        ///74858
        ///84168
        ///48683
        ///27367
        ///17375
        ///29693
        ///24358
        ///59227
        ///59229
        ///2 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Postleitzahl {
            get {
                return ResourceManager.GetString("Postleitzahl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 33,60
        ///98,33
        ///20,56
        ///12,96
        ///9,30
        ///16,51
        ///81,31
        ///31,02
        ///45,23
        ///0,65
        ///76,18
        ///4,01
        ///61,07
        ///86,48
        ///7,25
        ///92,08
        ///82,22
        ///60,19
        ///70,08
        ///39,83
        ///35,10
        ///94,86
        ///71,43
        ///76,69
        ///87,66
        ///52,48
        ///54,68
        ///68,28
        ///4,34
        ///22,68
        ///62,83
        ///16,91
        ///65,91
        ///77,35
        ///12,00
        ///34,54
        ///12,09
        ///1,20
        ///45,05
        ///66,64
        ///49,00
        ///74,97
        ///98,21
        ///25,79
        ///63,09
        ///20,47
        ///83,17
        ///81,58
        ///82,03
        ///98,68
        ///74,40
        ///77,30
        ///89,63
        ///85,15
        ///41,56
        ///84,65
        ///29,24
        ///32,27
        ///95,56
        ///29,88
        ///24,35
        ///25,57
        ///80,33
        ///16,10
        ///38,96
        ///62,78
        ///17,16
        ///78,50
        ///53,43
        ///87,08
        ///26,99
        ///22,37
        ///88,57
        ///51,60
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string preise_unter_100 {
            get {
                return ResourceManager.GetString("preise_unter_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 780,80
        ///467,96
        ///953,29
        ///308,17
        ///268,59
        ///544,22
        ///955,47
        ///569,53
        ///706,99
        ///310,21
        ///510,72
        ///167,86
        ///113,70
        ///888,93
        ///124,87
        ///277,59
        ///684,49
        ///230,13
        ///781,55
        ///958,63
        ///707,04
        ///380,39
        ///160,72
        ///169,76
        ///114,87
        ///433,54
        ///347,51
        ///842,43
        ///132,83
        ///450,07
        ///586,94
        ///977,04
        ///703,24
        ///991,88
        ///119,59
        ///537,91
        ///874,53
        ///772,32
        ///665,82
        ///668,61
        ///164,51
        ///640,86
        ///420,26
        ///746,77
        ///255,88
        ///388,17
        ///474,40
        ///293,51
        ///788,06
        ///855,55
        ///373,35
        ///744,59
        ///945,44
        ///641,92
        ///762,31
        ///606,28
        ///628,24
        ///794,41
        ///848,56
        ///563,59
        ///361,14
        ///934,87
        ///826,69
        ///534,63
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string preise_zwischen_100_und_1000 {
            get {
                return ResourceManager.GetString("preise_zwischen_100_und_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abich-Thiele-Straße
        ///Äbtissinnenweg
        ///Ackerröte
        ///Adam-von-Trott-Weg
        ///Adolf-Ellissen-Weg
        ///Adolf-Hoyer-Straße
        ///Adolf-Sievert-Straße
        ///Agnes-von-Plesse-Hof
        ///Ahornsteg
        ///Akazienweg
        ///Albanikirchhof
        ///Albaniplatz
        ///Albaniwall
        ///Albert-Einstein-Straße
        ///Albert-Müller-Straße
        ///Albert-Schweitzer-Straße
        ///Albrecht-Thaer-Weg
        ///Albrecht-von-Haller-Straße
        ///Albrechtstraße
        ///Alfred-Delp-Weg
        ///Alice-Rosenberg-Weg
        ///Allensteiner Weg
        ///Allerstraße
        ///Alte-Wollenweber-Weg
        ///Alva-Myrdal-Weg
        ///Am Alten Krug
        ///Am Bärenberge
        ///Am Bismarckstein
        ///Am B [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Straße {
            get {
                return ResourceManager.GetString("Straße", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die +1 (601) 909-7957
        ///+56 (468) 462-6253
        ///+63 (489) 290-6538
        ///+1 (200) 789-6798
        ///+63 (252) 494-7893
        ///+374 (857) 937-5419
        ///+62 (433) 831-6999
        ///+254 (607) 213-0434
        ///+48 (482) 461-8156
        ///+86 (414) 966-5241
        ///+86 (773) 203-3046
        ///+20 (984) 377-2496
        ///+86 (863) 761-5182
        ///+63 (852) 834-1106
        ///+86 (568) 322-8735
        ///+992 (165) 218-3151
        ///+86 (829) 518-3590
        ///+55 (607) 687-4910
        ///+51 (801) 512-4658
        ///+86 (448) 904-2001
        ///+62 (342) 713-8676
        ///+267 (894) 835-3361
        ///+55 (322) 192-1771
        ///+1 (403) 187-1588
        ///+855 (266) 403-6321
        ///+81 (995)  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Telefonnummern_weltweit {
            get {
                return ResourceManager.GetString("Telefonnummern_weltweit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 0:11
        ///18:20
        ///5:38
        ///10:25
        ///11:44
        ///19:45
        ///21:19
        ///18:09
        ///11:36
        ///8:26
        ///6:43
        ///1:59
        ///12:35
        ///15:48
        ///3:51
        ///15:21
        ///1:38
        ///21:19
        ///19:03
        ///18:27
        ///21:51
        ///10:30
        ///1:03
        ///21:10
        ///9:55
        ///23:28
        ///6:59
        ///20:40
        ///1:55
        ///11:28
        ///15:55
        ///18:10
        ///8:01
        ///8:29
        ///15:24
        ///18:53
        ///1:22
        ///0:36
        ///19:23
        ///15:08
        ///9:10
        ///12:47
        ///3:00
        ///10:35
        ///15:10
        ///5:33
        ///22:40
        ///5:28
        ///2:30
        ///1:42
        ///10:19
        ///18:03
        ///12:14
        ///23:08
        ///11:30
        ///21:14
        ///1:54
        ///12:58
        ///16:44
        ///11:24
        ///5:11
        ///7:16
        ///17:45
        ///5:53
        ///21:20
        ///22:02
        ///16:30
        ///23:30
        ///10:47
        ///11:00
        ///2:43
        ///13:20
        ///16:50
        ///6:09
        ///23:55
        ///10:48
        ///20:03
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string uhrzeit {
            get {
                return ResourceManager.GetString("uhrzeit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aaron
        ///Abdul
        ///Abel
        ///Abraham
        ///Achim
        ///Adam
        ///Adolf
        ///Adreon
        ///Adrian
        ///Adriano
        ///Adrien
        ///Aeneas
        ///Ahe
        ///Aheahe
        ///Aidan
        ///Aiden
        ///Aika
        ///Aimo
        ///Akamai
        ///Akamu
        ///Akela
        ///Aki
        ///Akoni
        ///Alain
        ///Alan
        ///Alarich
        ///Albert
        ///Albrecht
        ///Alec
        ///Alessandro
        ///Alessio
        ///Alex
        ///Alexander
        ///Alexej
        ///Alexis
        ///Alfons
        ///Alfred
        ///Ali
        ///Alika
        ///Aljoscha
        ///Allard
        ///Aloha
        ///Alois
        ///Alrik
        ///Alvaro
        ///Alwin
        ///Amadeus
        ///Amandus
        ///Amaranth
        ///Amel
        ///Amelio
        ///Amir
        ///Amiran
        ///Amon
        ///Anais
        ///Anakin
        ///Anders
        ///Andre
        ///Andrea
        ///Andreas
        ///Andrej
        ///Andres
        ///Andrew
        ///Andrico
        ///Andrik
        ///Angus
        ///Anian
        ///Ani [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string vorname_maennlich {
            get {
                return ResourceManager.GetString("vorname_maennlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aaliyah
        ///Aaltje
        ///Abbey
        ///Abigal
        ///Ada
        ///Adele
        ///Adelheid
        ///Adelina
        ///Adina
        ///Adrian
        ///Adriana
        ///Aenna
        ///Agatha
        ///Agnes
        ///Aida
        ///Aileen
        ///Aimée
        ///Aitana
        ///Aithne
        ///Ajlin
        ///Akela
        ///Alamea
        ///Alana
        ///Alani
        ///Alara
        ///Alaula
        ///Alba
        ///Alberte
        ///Alea
        ///Aleha
        ///Alena
        ///Alessa
        ///Alessandra
        ///Alessia
        ///Alex
        ///Alexa
        ///Alexandra
        ///Alexia
        ///Alexis
        ///Alexsandra
        ///Aleya
        ///Alica
        ///Alice
        ///Alicia
        ///Alida
        ///Aliena
        ///Alina
        ///Aline
        ///Alisa
        ///Alisha
        ///Alisia
        ///Alison
        ///Alissa
        ///Aliy
        ///Aliya
        ///Alizee
        ///Alla
        ///Allegra
        ///Allyssa
        ///Alma
        ///Almina
        ///Almuth
        ///Aloha
        ///Aluna
        ///Alva
        ///Alysa
        ///Alyssa
        /// [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string vorname_weiblich {
            get {
                return ResourceManager.GetString("vorname_weiblich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carie
        ///Marje
        ///Louie
        ///Tommie
        ///Englebert
        ///Alika
        ///Viole
        ///Toni
        ///Shelley
        ///Dell
        ///Andrus
        ///Nowell
        ///Daffie
        ///Vicki
        ///Dael
        ///Austin
        ///Marlie
        ///Rubetta
        ///Cori
        ///Vitia
        ///Leupold
        ///Colman
        ///Johann
        ///Inness
        ///Barry
        ///Si
        ///Jeni
        ///Bernadina
        ///Priscilla
        ///Adriane
        ///Benjy
        ///Jaime
        ///Kelci
        ///Austin
        ///Lauraine
        ///Rozanne
        ///Wendi
        ///Constantina
        ///Alanah
        ///Kessiah
        ///Rockie
        ///Krissie
        ///Hali
        ///Torrie
        ///Cobbie
        ///Wynny
        ///Shurwood
        ///Lyndell
        ///Phyllida
        ///Tiler
        ///Duane
        ///Xerxes
        ///Sibylle
        ///Drucill
        ///Nessy
        ///Silva
        ///Ariella
        ///Charmain
        ///Leupold
        ///Colan
        ///Sly
        ///Caz
        ///Rachel
        ///Amerigo
        ///Gilli [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string vornamen_gemischt_usa {
            get {
                return ResourceManager.GetString("vornamen_gemischt_usa", resourceCulture);
            }
        }
    }
}
